In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel("D:\\ML Projects\\Onusandhan\\Files\\Linear_Algebra_Data.xlsx")
df.head()

,Student Name,Quize_1,Midsem,Quize_2,Endsem_A,Endsem_B,Total_Marks
0,Ajay Kumar Kumawat,5.5,7.5,7.5,5,4.0,29.5
1,Akash Tarenia,4.0,7.0,5.0,10,6.0,32.0
2,Akash Uniyal,9.5,15.0,7.5,8,7.0,47.0
3,Anurag Kumar,5.0,8.0,8.5,5,3.5,30.0
4,Ariba,0.5,3.5,4.5,4,8.0,20.5

In [3]:
df.columns

Index(['Student Name', 'Quize_1', 'Midsem', 'Quize_2', 'Endsem_A', 'Endsem_B',
       'Total_Marks'],
      dtype='object')

In [4]:
df.isnull().sum()

Student Name    0
Quize_1         0
Midsem          0
Quize_2         0
Endsem_A        0
Endsem_B        0
Total_Marks     0
dtype: int64

In [5]:
df.describe()

         Quize_1     Midsem    Quize_2   Endsem_A   Endsem_B  Total_Marks
count  60.000000  60.000000  60.000000  60.000000  60.000000    60.000000
mean    5.066667  10.266667   6.650000   8.266667   7.500000    37.750000
std     3.338865   5.509212   2.625333   2.933539   4.719236    14.240221
min     0.000000   0.000000   0.000000   0.000000   0.000000    11.000000
25%     2.000000   6.375000   4.875000   6.000000   4.000000    28.750000
50%     5.250000   9.750000   7.000000   9.000000   6.500000    37.250000
75%     8.000000  14.000000   8.500000  10.000000  10.125000    50.000000
max    12.500000  23.000000  12.000000  14.000000  19.500000    71.500000